name: aoc2022dart
description: Advent of Code 2022
publish_to: "none"
version: 1.0.20

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  path: ^1.8.2
  directed_graph: ^0.3.7
  collection: ^1.17.0
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
