name: aoc2022dart
description: Advent of Code 2022
publish_to: "none"
version: 1.0.2

environment:
  sdk: ">=2.19.0-374.1.beta <3.0.0"

dependencies:
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
