name: aoc2022dart
description: Advent of Code 2022
publish_to: "none"
version: 1.0.4

environment:
  sdk: ">=2.19.0-374.1.beta <3.0.0"

dependencies:
  path: ^1.8.2
  tuples:
    git:
      url: git@github.com:sunderee/tuples.git
      ref: master
  dart_scope_functions:
    git:
      url: git@github.com:sunderee/dart-scope-functions.git
      ref: master
  stack:
    git:
      url: git@github.com:sunderee/stack.git
      ref: master

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
