name: aoc2022dart
description: Advent of Code 2022
publish_to: "none"
version: 1.0.11

environment:
  sdk: ">=2.19.0-444.1.beta <3.0.0"

dependencies:
  path: ^1.8.2
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
